apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    name: consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: localhost:32000/kubernetes_demo_consumer
          env:
            - name: API_SERVER_HOST
              value: "http://backend:5000"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbit:5672/%2F"
      restartPolicy: Always