version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - MONGODB_URI=localhost
      - FLASK_DEBUG=True
      - SECRET_KEY=fnu348nAFmn598TERNK235
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq
      - mongo
    network_mode: host
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
  mongo:
    image: mongo
    ports:
      - 27017:27017
  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    depends_on:
      - web
    network_mode: host
    environment:
      API_SERVER_HOST: http://localhost:5000
    command: /bin/sh -c "sleep 12; supervisord"
